@startuml

interface MetricInterface {
    getMetricData()
}

class Metric {
    metricData
--
    getMetricData()
-- Zobowiązanie --
Prezentacja statusu metryki
}

Metric -up-|> MetricInterface

interface MetrScallarReprezentInterface {
convertDataSet()
}

class MetrScallarReprezent {
dataSet
--
convertDataSet()
-- Zobowiązanie --
Zwraca skonwertowaną, 
przeliczoną, przetworzoną 
wartość liczbową
umożlwiającą wykonanie porównania
}

MetrScallarReprezent -up-|> MetrScallarReprezentInterface

interface DataSetInterface {
    getValue()
    getDate()
}

class DataSet {
    value
    data
--
    getData()
-- Zobowiązanie --
Pobiera zestaw danych 
do porównania
}

DataSet -left-|> DataSetInterface

MetrScallarReprezent .down.> DataSet

Metric .right.> MetrScallarReprezent

/'
interface DailyDateInterface {
    getValue()
    getDate()
    getImportType()
}

class DailyDate {
    string value
    string date
    importType
    getValue()
    getDate()
    getImportType()
-- Zobowiązanie --
Pobiera dane ze źródła
i zapisuje do bazy
}

DailyDate -right-|> DailyDateInterface

DataSet .right.> DailyDate
'/
@enduml
