@startuml

interface MetricInterface {
    getMetricStatus()
}

class Metric {
    metricStatus
--
    getMetricStatus()
-- Zobowiązanie --
Zwraca status metryki
}

Metric -up-|> MetricInterface

interface MetricCompareInterface {
compareData()
}

class MetricCompare {
currentdata
previousData
--
compareData()
}

MetricCompare -up-|> MetricCompareInterface

MetricCompare -right-> Metric

@enduml
