@startuml

class Import {
    string source
    string importName
    
}

interface MetricInterface {
    resultCMP()
    getDataSet()
}

class Metric {
    array currentValue
    array previousValue
--
    resultCMP()
    getDataSet()
-- Zobowiązanie --
Pobiera zestaw danych
i wywołuje metodę 
porównującą dane
}

interface DataSetInterface {
    getValue()
    getDate()
}

class DataSet {
    string value
    data data
--
    getValue()
    getDate()
-- Zobowiązanie --
Pobiera zestaw danych 
do porównania
}

interface DailyDateInterface {
    getValue()
    getDate()
    getImportType()
}

class DailyDate {
    string value
    string date
    importType
    getValue()
    getDate()
    getImportType()
-- Zobowiązanie --
Pobiera dane ze źródła
i zapisuje do bazy
}

DailyDate -right-|> DailyDateInterface

DataSet .up.> DailyDate

MetricInterface <|.right. Metric

DataSetInterface <|.left. DataSet

Metric .right.> DataSet

interface ResultCompareInterface {
    resultCompare()
    saveResultCompare()
    sendNotification()
}

class ResultCompare {
    array dataSet
--
    resultCompare()
    sendNotification()
    saveResultCompare()
-- Zobowiązanie --
Porównuje aktualny zestaw danych
z danymi z poprzedniego okresu
}

interface SaveResultCompareInterface {
    setCurValue()
    setPrevValue()
    setResultCompare()
    setResultCompareDate()
}

class SaveResultCompare {
    string curValue
    string prevValue
    string resultCompare
    date resultCompareDate
--
    setCurValue()
    setPrevValue()
    setResultCompare()
    setResultCompareDate()
-- Zobowiązanie --
Zapisuje do bazy:
porównywane dane
status porównania
}

SaveResultCompare -left-|> SaveResultCompareInterface

ResultCompareInterface <|-left- ResultCompare

ResultCompare <.down. Metric

ResultCompare .down.> SaveResultCompare

interface NotificationInterface {
    sendNotification()
}

class Notification {
string mailTo
string message
string comparedMetrics
--
sendNotification()
-- Zobowiązanie --
Wysyła powiadomienia
w przypadku
gdy metryki pogarszają się
}

Notification <.down. ResultCompare

NotificationInterface <|.left. Notification

interface CompareMethodInterface {
    compareMethod()
}

class CompareMethod {
    string method
--
    compareMethod()
-- Zobowiązanie --
Zwraca dostępne 
metody porównania
}

CompareMethod -left-|> CompareMethodInterface

ResultCompare .left.> CompareMethod

/'
enum Result{
    LESS
    EQ
    GRATER    
}
'/

@enduml